In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [12]:
df = pd.read_csv('rental_canada.csv')
df.head()

,Unnamed: 0,title,description,price,date_posted,address,url
0,0,20'/40' - STORAGE CONTAINERS FOR SALE & RENT!!,Get only the ***best units*** at the lowest ...,"$3,200.00",17/03/2023,Calgary,/v-storage-parking/calgary/20-40-storage-conta...
1,1,Renovated 1 Bedroom For Rent - Forest Hill,Bachelor and 1 bedroom apartments Ready to R...,"$2,049.00",17/03/2023,City of Toronto,/v-apartments-condos/city-of-toronto/renovated...
2,2,The Onyx - 2 Bedroom Apartment for Rent,Ironclad Properties presents The Onyx! Embra...,"$1,748.00",30/03/2023,Winnipeg,/v-apartments-condos/winnipeg/the-onyx-2-bedro...
3,3,Campling Ave - 3 Bedroom Upper Suite House for...,Welcome to 5659A Campling Avenue! These ...,"$1,530.00",06/04/2023,Regina,/v-apartments-condos/regina/campling-ave-3-bed...
4,4,MUST SEE! 1 BED APARTMENT FOR RENT NEAR BRITAN...,LIMITED TIME OFFER: $500 MOVE-IN INCENTIVE ...,"$1,825.00",29/03/2023,Ottawa,/v-apartments-condos/ottawa/must-see-1-bed-apa...

In [13]:
# https://www.kijiji.ca append to all url value
df['url'] = 'https://www.kijiji.ca' + df['url']
df.head()

,Unnamed: 0,title,description,price,date_posted,address,url
0,0,20'/40' - STORAGE CONTAINERS FOR SALE & RENT!!,Get only the ***best units*** at the lowest ...,"$3,200.00",17/03/2023,Calgary,https://www.kijiji.ca/v-storage-parking/calgar...
1,1,Renovated 1 Bedroom For Rent - Forest Hill,Bachelor and 1 bedroom apartments Ready to R...,"$2,049.00",17/03/2023,City of Toronto,https://www.kijiji.ca/v-apartments-condos/city...
2,2,The Onyx - 2 Bedroom Apartment for Rent,Ironclad Properties presents The Onyx! Embra...,"$1,748.00",30/03/2023,Winnipeg,https://www.kijiji.ca/v-apartments-condos/winn...
3,3,Campling Ave - 3 Bedroom Upper Suite House for...,Welcome to 5659A Campling Avenue! These ...,"$1,530.00",06/04/2023,Regina,https://www.kijiji.ca/v-apartments-condos/regi...
4,4,MUST SEE! 1 BED APARTMENT FOR RENT NEAR BRITAN...,LIMITED TIME OFFER: $500 MOVE-IN INCENTIVE ...,"$1,825.00",29/03/2023,Ottawa,https://www.kijiji.ca/v-apartments-condos/otta...

In [14]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [15]:
df.to_csv('rental_canada_new.csv')

In [32]:
df1 = pd.read_csv('kijiji_toronto_apartments_300.csv')
df2 = pd.read_csv('kijiji_toronto_apartments_new.csv')
df3 = pd.concat([df1, df2])

In [33]:
df3['description'] = df3['description'].str.replace('Description', '')
df3.head()

,title,price,description,date_posted,address,url
0,Private office space for 3 persons in Liberty ...,Please Contact,Productive workspace for three that comes with...,2023-04-03 13:02:10,"3601 Highway 7, Suite 400, Toronto, ON, L3R 0M3",https://www.kijiji.ca/v-commercial-office-spac...
1,Room available for female Markham rd and paint...,$675,Private room available for rent for a female\n...,2023-04-03 10:24:53,"23 Bailey Cres, Toronto, M1G 2P4",https://www.kijiji.ca/v-room-rental-roommate/c...
2,Looking for a lease!?!,"$2,500",Stunning 2 Bedroom Corner Unit In A Less Than ...,2023-04-02 23:36:57,"20 Orchid Place Drive, Scarborough, Toronto, ON",https://www.kijiji.ca/v-apartments-condos/city...
3,Shared Accommodation for boys,$420,Accommodation available for 3 Malayali boys.\n...,2023-04-02 23:32:49,"Lawrence Ave E, Toronto, ON, M1R 2Z1",https://www.kijiji.ca/v-short-term-rental/city...
4,Sharing accommodation for girls and boys India...,$550,accomodation available for girls and boys\n(Pr...,2023-04-02 22:29:09,"20 Tuxedo Ct, Scarborough, ON M1G 3S5, Canada",https://www.kijiji.ca/v-room-rental-roommate/c...

In [34]:
# convert date_posted to dd/mm/yyyy format
df3['date_posted'] = pd.to_datetime(df3['date_posted'])
df3['date_posted'] = df3['date_posted'].dt.strftime('%d/%m/%Y')
df3.head()

,title,price,description,date_posted,address,url
0,Private office space for 3 persons in Liberty ...,Please Contact,Productive workspace for three that comes with...,03/04/2023,"3601 Highway 7, Suite 400, Toronto, ON, L3R 0M3",https://www.kijiji.ca/v-commercial-office-spac...
1,Room available for female Markham rd and paint...,$675,Private room available for rent for a female\n...,03/04/2023,"23 Bailey Cres, Toronto, M1G 2P4",https://www.kijiji.ca/v-room-rental-roommate/c...
2,Looking for a lease!?!,"$2,500",Stunning 2 Bedroom Corner Unit In A Less Than ...,02/04/2023,"20 Orchid Place Drive, Scarborough, Toronto, ON",https://www.kijiji.ca/v-apartments-condos/city...
3,Shared Accommodation for boys,$420,Accommodation available for 3 Malayali boys.\n...,02/04/2023,"Lawrence Ave E, Toronto, ON, M1R 2Z1",https://www.kijiji.ca/v-short-term-rental/city...
4,Sharing accommodation for girls and boys India...,$550,accomodation available for girls and boys\n(Pr...,02/04/2023,"20 Tuxedo Ct, Scarborough, ON M1G 3S5, Canada",https://www.kijiji.ca/v-room-rental-roommate/c...

In [35]:
# Extract city name from address column
def extract_city(address):
    cities = ['brampton', 'mississauga', 'don mills', 'toronto', 'ajax', 'markham', 'scarborough', 'north york']
    for city in cities:
        if isinstance(address, str):
            if city in address.lower():
                return city.title()
    return 'Other'

df3['address'] = df3['address'].apply(extract_city)

grouped = df3.groupby('address')
for name, group in grouped:
    print(f"{name}: {len(group)}")

Brampton: 123
Don Mills: 36
Markham: 27
Mississauga: 24
North York: 237
Other: 98
Scarborough: 122
Toronto: 236

In [36]:
df3.head()

,title,price,description,date_posted,address,url
0,Private office space for 3 persons in Liberty ...,Please Contact,Productive workspace for three that comes with...,03/04/2023,Toronto,https://www.kijiji.ca/v-commercial-office-spac...
1,Room available for female Markham rd and paint...,$675,Private room available for rent for a female\n...,03/04/2023,Toronto,https://www.kijiji.ca/v-room-rental-roommate/c...
2,Looking for a lease!?!,"$2,500",Stunning 2 Bedroom Corner Unit In A Less Than ...,02/04/2023,Toronto,https://www.kijiji.ca/v-apartments-condos/city...
3,Shared Accommodation for boys,$420,Accommodation available for 3 Malayali boys.\n...,02/04/2023,Toronto,https://www.kijiji.ca/v-short-term-rental/city...
4,Sharing accommodation for girls and boys India...,$550,accomodation available for girls and boys\n(Pr...,02/04/2023,Scarborough,https://www.kijiji.ca/v-room-rental-roommate/c...

In [38]:
print(df.shape)
df = pd.concat([df, df3])
df.shape

(2586, 6)

(3489, 6)

In [39]:
df.to_csv('final_data.csv')